#!/usr/bin/env python3
"""
Plot MEV analysis results from the CSV file generated by the Rust analyzer.

Usage:
    python plot_mev.py [--input mev_per_slot_24h.csv]
"""

import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.dates as mdates
from datetime import datetime
import argparse
import sys

def plot_mev_data(csv_file='mev_per_slot_24h.csv', output_dir='.'):
    """Plot MEV data from CSV file."""

    # Read CSV
    try:
        df = pd.read_csv(csv_file)
        print(f"✅ Loaded {len(df)} slots from {csv_file}")
    except FileNotFoundError:
        print(f"❌ Error: File '{csv_file}' not found!")
        sys.exit(1)

    # Convert timestamp to datetime
    df['datetime'] = pd.to_datetime(df['timestamp'], unit='s', errors='coerce')

    # Filter out rows with no timestamp
    df_valid = df[df['datetime'].notna()].copy()

    if len(df_valid) == 0:
        print("❌ Error: No valid timestamps found in data!")
        sys.exit(1)

    print(f"📊 Statistics:")
    print(f"   Total slots: {len(df_valid)}")
    print(f"   Slots with MEV: {len(df_valid[df_valid['mev_events'] > 0])}")
    print(f"   Total MEV profit: {df_valid['total_profit_sol'].sum():.4f} SOL")
    print(f"   Max MEV in single slot: {df_valid['total_profit_sol'].max():.4f} SOL")

    # Create figure with subplots
    fig, axes = plt.subplots(3, 1, figsize=(14, 12))
    fig.suptitle('Solana MEV Analysis - 24 Hours', fontsize=16, fontweight='bold')

    # Plot 1: MEV Profit per Slot
    ax1 = axes[0]
    ax1.scatter(df_valid['datetime'], df_valid['total_profit_sol'],
                alpha=0.6, s=20, c='#14F195', edgecolors='none')
    ax1.set_ylabel('MEV Profit (SOL)', fontsize=12)
    ax1.set_title('MEV Profit per Slot', fontsize=13, fontweight='bold')
    ax1.grid(True, alpha=0.3)
    ax1.xaxis.set_major_formatter(mdates.DateFormatter('%H:%M'))
    ax1.tick_params(axis='x', rotation=45)

    # Plot 2: Number of MEV Events
    ax2 = axes[1]
    ax2.scatter(df_valid['datetime'], df_valid['mev_events'],
                alpha=0.6, s=20, c='#9945FF', edgecolors='none')
    ax2.set_ylabel('Number of MEV Events', fontsize=12)
    ax2.set_title('MEV Events per Slot', fontsize=13, fontweight='bold')
    ax2.grid(True, alpha=0.3)
    ax2.xaxis.set_major_formatter(mdates.DateFormatter('%H:%M'))
    ax2.tick_params(axis='x', rotation=45)

    # Plot 3: Event Type Breakdown
    ax3 = axes[2]
    ax3.scatter(df_valid['datetime'], df_valid['arbitrage_count'],
                alpha=0.6, s=15, c='#14F195', label='Arbitrage', edgecolors='none')
    ax3.scatter(df_valid['datetime'], df_valid['sandwich_count'],
                alpha=0.6, s=15, c='#FF6B6B', label='Sandwich', edgecolors='none')
    ax3.set_xlabel('Time (UTC)', fontsize=12)
    ax3.set_ylabel('Event Count', fontsize=12)
    ax3.set_title('MEV Event Types', fontsize=13, fontweight='bold')
    ax3.legend(loc='upper right')
    ax3.grid(True, alpha=0.3)
    ax3.xaxis.set_major_formatter(mdates.DateFormatter('%H:%M'))
    ax3.tick_params(axis='x', rotation=45)

    plt.tight_layout()

    # Save plot
    output_file = f"{output_dir}/mev_analysis_plot.png"
    plt.savefig(output_file, dpi=300, bbox_inches='tight')
    print(f"\n✅ Plot saved to: {output_file}")

    # Show plot
    plt.show()

    # Create a rolling average plot
    fig2, ax = plt.subplots(figsize=(14, 6))

    # Calculate rolling average (e.g., over 100 slots)
    window_size = min(100, len(df_valid) // 10)
    df_valid['profit_rolling_avg'] = df_valid['total_profit_sol'].rolling(
        window=window_size, min_periods=1
    ).mean()

    ax.plot(df_valid['datetime'], df_valid['profit_rolling_avg'],
            linewidth=2, color='#9945FF', label=f'Rolling Average ({window_size} slots)')
    ax.fill_between(df_valid['datetime'], 0, df_valid['profit_rolling_avg'],
                     alpha=0.3, color='#9945FF')

    ax.set_xlabel('Time (UTC)', fontsize=12)
    ax.set_ylabel('Average MEV Profit (SOL)', fontsize=12)
    ax.set_title(f'MEV Profit Rolling Average - {window_size} Slot Window',
                 fontsize=14, fontweight='bold')
    ax.legend(loc='upper right')
    ax.grid(True, alpha=0.3)
    ax.xaxis.set_major_formatter(mdates.DateFormatter('%H:%M'))
    plt.xticks(rotation=45)

    plt.tight_layout()

    # Save rolling average plot
    output_file2 = f"{output_dir}/mev_rolling_average.png"
    plt.savefig(output_file2, dpi=300, bbox_inches='tight')
    print(f"✅ Rolling average plot saved to: {output_file2}")

    plt.show()

def main():
    parser = argparse.ArgumentParser(
        description='Plot MEV analysis results from CSV file'
    )
    parser.add_argument(
        '--input',
        default='mev_per_slot_24h.csv',
        help='Input CSV file (default: mev_per_slot_24h.csv)'
    )
    parser.add_argument(
        '--output-dir',
        default='.',
        help='Output directory for plots (default: current directory)'
    )

    args = parser.parse_args()

    print("🎨 Generating MEV analysis plots...\n")
    plot_mev_data(args.input, args.output_dir)
    print("\n✨ Done!")

if __name__ == '__main__':
    main()
